import type { LegalDoc } from './types'

const termsEn: LegalDoc = {
  slug: 'terms',
  locale: 'en',
  title: 'Terms of Service',
  metaTitle: 'Terms of Service | CodeAgentSwarm',
  metaDescription:
    'The terms that govern your use of the CodeAgentSwarm desktop application and website, including acceptable use, third-party AI tools, warranties and liability.',
  lastUpdated: '2026-06-22',
  intro:
    'These Terms of Service ("Terms") govern your use of the CodeAgentSwarm desktop application, website and related services (together, the "Service"). Please read them carefully. By downloading, installing or using the Service you agree to these Terms. If you do not agree, do not use the Service.',
  sections: [
    {
      id: 'provider',
      title: 'Who we are',
      blocks: [
        {
          type: 'paragraph',
          text: 'The Service is provided by Arturo Garcia, an individual based in Ciudad Real, Spain (the "Provider", "we", "us"). You can reach us at hello@codeagentswarm.com.',
        },
      ],
    },
    {
      id: 'service',
      title: 'What the Service is',
      blocks: [
        {
          type: 'paragraph',
          text: 'CodeAgentSwarm is a desktop application that lets you run and manage multiple third-party AI command-line coding tools (such as Claude Code, OpenAI Codex and Gemini CLI) in parallel, with task management, change tracking and related features. The Service is a client that orchestrates those tools on your own computer.',
        },
        {
          type: 'callout',
          variant: 'warning',
          text: 'CodeAgentSwarm is not an AI model and does not produce AI output itself. The AI tools you run are operated by their own providers under their own terms. You are responsible for having a valid account or API key for each tool you use.',
        },
      ],
    },
    {
      id: 'eligibility',
      title: 'Eligibility',
      blocks: [
        {
          type: 'paragraph',
          text: 'You must be at least 16 years old and able to enter into a binding agreement to use the Service. If you use the Service on behalf of an organisation, you confirm you are authorised to accept these Terms on its behalf.',
        },
      ],
    },
    {
      id: 'accounts',
      title: 'Accounts',
      blocks: [
        {
          type: 'paragraph',
          text: 'Some features require an account, created through a third-party sign-in (GitHub, Google or Discord). You are responsible for the activity under your account and for keeping access to it secure. Notify us promptly of any unauthorised use.',
        },
      ],
    },
    {
      id: 'license',
      title: 'Licence to use the Service',
      blocks: [
        {
          type: 'paragraph',
          text: 'We grant you a personal, limited, non-exclusive, non-transferable and revocable licence to install and use the Service for your own software development purposes, subject to these Terms. We retain all rights not expressly granted to you.',
        },
      ],
    },
    {
      id: 'acceptable-use',
      title: 'Acceptable use',
      blocks: [
        {
          type: 'paragraph',
          text: 'You agree not to:',
        },
        {
          type: 'list',
          items: [
            'Use the Service for any unlawful purpose or in violation of any applicable law.',
            'Reverse engineer, decompile or attempt to extract the source code of the Service, except to the extent this restriction is prohibited by law.',
            'Resell, sublicense or commercially redistribute the Service without our permission.',
            'Interfere with, overload or attempt to gain unauthorised access to the Service, our backend or other users.',
            'Use the Service to build a directly competing product by copying it.',
            'Abuse the in-app help assistant, for example by trying to circumvent usage limits or extract the underlying system.',
          ],
        },
      ],
    },
    {
      id: 'third-party',
      title: 'Third-party tools and services',
      blocks: [
        {
          type: 'paragraph',
          text: 'The Service works alongside third-party tools and services, including AI CLIs (Anthropic Claude Code, OpenAI Codex, Google Gemini CLI), OAuth providers (GitHub, Google, Discord), payment processing (Stripe) and others. Your use of those is governed by their own terms and privacy policies. We are not responsible for their availability, content, output, pricing or conduct, and we do not control them.',
        },
      ],
    },
    {
      id: 'ai-output',
      title: 'AI output and your responsibility',
      blocks: [
        {
          type: 'callout',
          variant: 'warning',
          text: 'Code, suggestions and other content generated by the AI tools you run can be inaccurate, insecure or incomplete. You are solely responsible for reviewing, testing and deciding whether to use any AI-generated output. Do not run commands or ship code you do not understand. We are not responsible for any consequences of AI-generated output, including data loss or damage to your systems.',
        },
      ],
    },
    {
      id: 'subscriptions',
      title: 'Plans, payments and refunds',
      blocks: [
        {
          type: 'paragraph',
          text: 'The Service may be offered free of charge and/or through paid plans. If you purchase a paid plan, the price, billing period and features will be shown at the time of purchase. Payments are processed by Stripe. Unless stated otherwise, subscriptions renew automatically until cancelled, and you can cancel at any time with effect at the end of the current billing period.',
        },
        {
          type: 'paragraph',
          text: 'If you are a consumer in the EU, you have a statutory right of withdrawal within 14 days of purchase, subject to the legal exceptions for digital content you have started to use. Any mandatory consumer rights under Spanish and EU law are not affected by these Terms.',
        },
      ],
    },
    {
      id: 'ip',
      title: 'Intellectual property',
      blocks: [
        {
          type: 'paragraph',
          text: 'The Service, including its software, design, trademarks and content, is owned by the Provider or its licensors and is protected by intellectual property laws. These Terms do not transfer any ownership to you. Anything you create using the Service (such as your own code) remains yours.',
        },
      ],
    },
    {
      id: 'warranty',
      title: 'Disclaimer of warranties',
      blocks: [
        {
          type: 'paragraph',
          text: 'The Service is provided "as is" and "as available", without warranties of any kind, whether express or implied, including but not limited to fitness for a particular purpose, merchantability, accuracy and non-infringement. We do not warrant that the Service will be uninterrupted, error-free or secure, or that it will meet your requirements. This does not exclude any warranty that cannot be excluded under applicable law.',
        },
      ],
    },
    {
      id: 'liability',
      title: 'Limitation of liability',
      blocks: [
        {
          type: 'paragraph',
          text: 'To the maximum extent permitted by law, the Provider will not be liable for any indirect, incidental, special, consequential or punitive damages, or for any loss of data, profits, revenue or business, arising out of or related to your use of (or inability to use) the Service, even if advised of the possibility. To the extent we are found liable, our total aggregate liability is limited to the greater of the amount you paid us for the Service in the twelve months before the event giving rise to the claim, or fifty euros (EUR 50).',
        },
        {
          type: 'paragraph',
          text: 'Nothing in these Terms limits liability that cannot be limited by law, such as liability for fraud, gross negligence or death or personal injury caused by negligence, or your mandatory rights as a consumer.',
        },
      ],
    },
    {
      id: 'indemnity',
      title: 'Indemnification',
      blocks: [
        {
          type: 'paragraph',
          text: 'You agree to indemnify and hold the Provider harmless from any claims, damages or expenses arising from your misuse of the Service or your breach of these Terms or of applicable law.',
        },
      ],
    },
    {
      id: 'termination',
      title: 'Termination',
      blocks: [
        {
          type: 'paragraph',
          text: 'You may stop using the Service at any time. We may suspend or terminate your access if you breach these Terms or use the Service in a way that could harm us, other users or third parties. Provisions that by their nature should survive termination (such as intellectual property, disclaimers and limitation of liability) will continue to apply.',
        },
      ],
    },
    {
      id: 'changes',
      title: 'Changes to these Terms',
      blocks: [
        {
          type: 'paragraph',
          text: 'We may update these Terms from time to time. We will update the "Last updated" date and, for material changes, provide reasonable notice. Continued use of the Service after changes take effect means you accept the updated Terms.',
        },
      ],
    },
    {
      id: 'law',
      title: 'Governing law and jurisdiction',
      blocks: [
        {
          type: 'paragraph',
          text: 'These Terms are governed by Spanish law. Any dispute will be subject to the courts of Ciudad Real, Spain, except where mandatory consumer protection law gives you the right to bring proceedings in the courts of your place of residence within the EU.',
        },
      ],
    },
    {
      id: 'contact',
      title: 'Contact',
      blocks: [
        {
          type: 'paragraph',
          text: 'Questions about these Terms can be sent to hello@codeagentswarm.com.',
        },
      ],
    },
  ],
}

export default termsEn
